name: validate-code

on:
  pull_request:
    paths:
      - app/main.go

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.15
      - uses: actions/checkout@v1
      - run: go build app/main.go